org: "deisci"
pull_policy: "Always"
docker_tag: canary
platform_domain: ""
dhparam: ""
# limits_cpu: "100m"
# limits_memory: "50Mi"

# Any custom router annotations(https://github.com/deis/router#annotations)
# which need to be applied can be specified as key-value pairs under "deployment_annotations"
deployment_annotations:
  #<example-key>: <example-value>

# Any custom annotations for k8s services like http://kubernetes.io/docs/user-guide/services/#ssl-support-on-aws
# which need to be applied can be specified as key-value pairs under "service_annotations"
service_annotations:
  #<example-key>: <example-value>

# Enable to pin router pod hostPort when using minikube or vagrant
host_port:
  enabled: false

# Service type default to LoadBalancer 
# service_type: LoadBalancer
