apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-router
  namespace: deis
  labels:
    app: deis-router
  annotations:
    routerConfig: '{"useProxyProtocol":false}'
spec:
  replicas: 1
  selector:
    app: deis-router
  template:
    metadata:
      labels:
        app: deis-router
    spec:
      containers:
      - name: deis-router
        image: ## Image is dynamically set by `make set-image` as part of dev deployment ##
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
