apiVersion: v1
kind: Service
metadata:
  name: deis-router
{{- if .Values.service_annotations }}
  annotations:
{{- range $key, $value := .Values.service_annotations }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
  labels:
    heritage: deis
spec:
  type: LoadBalancer
  selector:
    app: deis-router
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 6443
    - name: builder
      port: 2222
      targetPort: 2222
    - name: healthz
      port: 9090
      targetPort: 9090
