{{- if not .Values.global.experimental_native_ingress }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deis-router
  labels:
    heritage: deis
{{ end }}{{/* if not .Values.global.experimental_native_ingress */}}
